version: '3.8'

services:
  # Next.js application with SQLite
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rural-women-rising-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/production.db
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      # Persist SQLite database
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
